Repository slurpcode/join-our-team, pull requests merged in 2022-10, with the labels that each got.

#94 Add auto join
  .github/ISSUE_TEMPLATE/invitation.yml
  .github/workflows/invitation.yml
  README.md
  README_ES.md
  README_ID.md
  README_JO.md
  README_TR.md
Labels: enhancement

#97 Adding Persian (Support Iranian)
  README.md
  README_ES.md
  README_FA.md
  README_ID.md
  README_JO.md
  README_PT.md
  README_TR.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#98 Improve
  README_FA.md
  README_JO.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#99 Remove `all-contributors`. Add `contrib.rocks`
  README.md
Labels: documentation
